CREATE TABLE species
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    phonetic       VARCHAR(255),
    diet           VARCHAR(255)                            NOT NULL,
    size           VARCHAR(255)                            NOT NULL,
    time_period    VARCHAR(255)                            NOT NULL,
    locations      TEXT[]                                  NOT NULL,
    classification TEXT[]                                  NOT NULL,
    images         TEXT[],
    CONSTRAINT pk_species PRIMARY KEY (id)
);

ALTER TABLE species
    ADD CONSTRAINT uc_species_name UNIQUE (name);